<footer class="py-3 my-4">
            <div class="row text-center m-0">
                <div class="col-lg-6" id="schedules">
                    <h2 class="m-5">Horaires d'ouvertures</h2>
                    <div>
                        <ul id="list-schedules">
                            <!-- Schedules is generated by getSchedules.js -->
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="m-5">Coordonnées</h2>
                    <div>
                        <p>
                            Garage V.PARROT <br>
                            123 Rue de l'imaginaire, 31555 Toulouse
                        </p>
                        <p>
                            06-XX-XX-XX-XX <br>
                            contact@garagevparrot.fr
                        </p>
                    </div>
                </div>
            </div>
            <ul class="nav justify-content-center border-bottom py-3 my-3">
                <li class="nav-item m-2"><a href="index.php">Accueil</a></li>
                <li class="nav-item m-2"><a href="exposition_cars.php">Véhicules</a></li>
                <li class="nav-item m-2"><a href="connexion.php">Connexion</a></li>
            </ul>
            <p class="text-center text-body-secondary">© 2024 Garage V.Parrot, Inc</p>
        </footer>
    </div>

    <script src="App/script/getSchedules.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>